env:
  es6: true
  browser: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
