name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install
      run: npm ci
    - name: Test
      run: npm test
      env:
        CI: true
        X_USE_PHANTOM: 1
    - name: Lint
      run: npm run lint
    - name: Check client.min.js
      run: |
        npm run minify
        git update-index --refresh
        git diff-index HEAD
